#MENUS
Doner Kebab: '7,80€'
Doner Kebab-S: '7,80€'
Doner Kebab-F: '7,80€'
Yufka Kebab galette: '8,50€'
Yufka Kebab galette-S: '8,50€'
Yufka Kebab galette-F: '8,50€'
Lahmacun Kebab: '9,60€'
Lahmacun Kebab-S: '9,60€'
Lahmacun Kebab-F: '9,60€'
Hamburger: '7,60€'
Hamburger-S: '7,60€'
Hamburger-F: '7,60€'
Sis tavuk: '8,40€'
Sis tavuk-S: '8,40€'
Sis tavuk-F: '8,40€'
Mergez / Sucuk: '7,40€'
Mergez / Sucuk-S: '7,40€'
Mergez / Sucuk-F: '7,40€'
Tacos 1: '8,50€'
Tacos 1-S: '8,50€'
Tacos 1-F: '8,50€'
Tacos 2: '11,20€'
Tacos 2-S: '11,20€'
Tacos 2-F: '11,20€'
Tacos 3: '13,20€'
Tacos 3-S: '13,20€'
Tacos 3-F: '13,20€'
Excellence Kebab: '11,20€'
Excellence Kebab-S: '11,20€'
Excellence Kebab-F: '11,20€'
Excellence Durum x2: '13,20€'
Excellence Durum x2-S: '13,20€'
Excellence Durum x2-F: '13,20€'
Soupe de lentille: '4,60€'
Soupe de lentille-S: '4,60€'
Soupe de lentille-F: '4,60€'
Menu enfant: '5,90€'
acc-viande1: '4,80€'
acc-viande2: '6,20€'
acc-feta: '0,95€'
acc-cheddar: '0,60€'
