-------------------------------------MENUS-------------------------------------
Doner Kebab: '7,80€'
Yufka Kebab galette: '8,50€'
Lahmacun Kebab: '9,60€'
Hamburger: '7,60€'
Sis tavuk: '8,40€'
Mergez / Sucuk: '7,40€'
Tacos 1: '8,50€'
Tacos 2: '11,20€'
Tacos 3: '13,20€'
Excellence Kebab: '11,20€'
Excellence Durum x2: '13,20€'
Soupe de lentille: '4,60€'
Menu enfant: '5,90€'
