Doner Kebab: '8,50€'
Doner Kebab-S: '5,00€'
Doner Kebab-F: '7,50€'
Yufka Kebab galette: '8,50€'
Yufka Kebab galette-S: '6,00€'
Yufka Kebab galette-F: '7,20€'
Lahmacun Kebab: '9,60€'
Lahmacun Kebab-S: '6,80€'
Lahmacun Kebab-F: '7,20€'
Hamburger: '7,60€'
Hamburger-S: '4,70€'
Hamburger-F: '6,80€'
Sis tavuk: '8,50€'
Sis tavuk-S: '6,00€'
Sis tavuk-F: '7,20€'
Mergez / Sucuk: '7,40€'
Mergez / Sucuk-S: '4,50€'
Mergez / Sucuk-F: '5,80€'
Tacos 1: '8,50€'
Tacos 1-S: '6,00€'
Tacos 1-F: '7,20€'
Tacos 2: '11,20€'
Tacos 2-S: '8,20€'
Tacos 2-F: '9,60€'
Tacos 3: '13,20€'
Tacos 3-S: '10,20€'
Tacos 3-F: '11,60€'
Excellence Kebab: '13,20€'
Excellence Kebab-S: '9,60€'
Excellence Kebab-F: '11,60€'
Excellence Durum x2: '13,20€'
Excellence Durum x2-S: '10,20€'
Excellence Durum x2-F: '11,60€'
Soupe de lentille: '4,60€'
Menu enfant: '6,20€'
acc-viande1: '4,80€'
acc-viande2: '6,20€'
acc-feta: '0,95€'
acc-cheddar: '0,60€'
ass-doner: '9,85€'
ass-iskender: '11,40€'
ass-steak: '9,20€'
ass-cotelettes-agneau: '11,40€'
ass-cordon: '9,65€'
ass-sis-tavuk: '10,40€'
ass-merguez: '8,60€'
ass-excellence: '15,20€'
ass-nuggets: '8,20€'
sal-feta: '6,90€'
sal-kebab: '8,40€'
sal-2viandes: '9,60€'
cous-semoule: '7,40€'
cous-merguez: '4,00€'
cous-brochette-poulet: '3,40€'
cous-boulettes: '4,00€'
cous-brochette-agneau: '3,60€'
cous-gigot: '4,80€'
